services:
  - type: web
    name: orbe-backend
    env: python
    rootDir: .
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: URL_SUPABASE
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
  - type: web
    name: orbe-frontend
    env: python
    rootDir: .
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: URL_SUPABASE
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ORBE_API_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
